# Generated by Django 4.2.7 on 2023-12-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia_conducir', models.CharField(max_length=20)),
                ('permiso_flete', models.CharField(max_length=20)),
                ('conductor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.conductor')),
            ],
        ),
    ]
