# Generated by Django 4.2.7 on 2023-12-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_conductor_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='apellido',
            field=models.CharField(default='DefaultLastName', max_length=100),
        ),
    ]
