# Generated by Django 4.2.7 on 2023-12-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conductor_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
    ]
