# Generated by Django 4.2.7 on 2023-12-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_conductor_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo_images/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo_images/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo_images/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculo_images/'),
        ),
    ]
