# Generated by Django 4.2.7 on 2023-12-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_vehiculo_image_1_vehiculo_image_2_vehiculo_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='imagen_conductor',
            field=models.ImageField(blank=True, null=True, upload_to='conductor_images/'),
        ),
    ]
