# Generated by Django 4.2.7 on 2023-12-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_solicitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='calle',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='provincia',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='calle_destino',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='calle_origen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ciudad_destino',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='ciudad_origen',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numeracion_destino',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='numeracion_origen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='provincia_destino',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='provincia_origen',
            field=models.CharField(default='', max_length=100),
        ),
    ]
