# Generated by Django 4.2.7 on 2023-12-03 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_solicitud_calle_remove_solicitud_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetos', models.ManyToManyField(to='api.objeto')),
            ],
        ),
        migrations.AddField(
            model_name='solicitud',
            name='carga',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.carga'),
        ),
    ]
