# Generated by Django 4.2.7 on 2023-12-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_objeto_carga_solicitud_carga'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='alto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objeto',
            name='ancho',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objeto',
            name='caracteristica',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='objeto',
            name='peso',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
