# Generated by Django 4.2.7 on 2023-12-03 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_objeto_alto_objeto_ancho_objeto_caracteristica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_login',
        ),
    ]
